name: Check README on push

on: [push, pull_request]

jobs:
  readme-tree-writer:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - uses: actions/checkout@v3
      # creates tree structure of repo
      - name: Write tree outputs to README
        uses: shirakiya/readme-tree-writer@v2
      # check diff of readme.md
      - name: Commit if diff exists
        run: |
          if [ "$(git diff --ignore-space-at-eol . | wc -l)" -gt "0" ]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "commit by shirakiya/readme-tree-writer"
            git push
          fi
